del C:\Users\gsaini\Documents\GitHub\Algo\Anagrams\Anagrams\ReadMe.txt
del C:\Users\gsaini\Documents\GitHub\Algo\BalancedBrackets\BalancedBrackets\ReadMe.txt
del C:\Users\gsaini\Documents\GitHub\Algo\BooksAndStudent\BooksAndStudent\ReadMe.txt
del C:\Users\gsaini\Documents\GitHub\Algo\BST\BST\ReadMe.txt
del C:\Users\gsaini\Documents\GitHub\Algo\Cycle\Cycle\ReadMe.txt
del C:\Users\gsaini\Documents\GitHub\Algo\Graph\Graph\ReadMe.txt
del C:\Users\gsaini\Documents\GitHub\Algo\GrayCode\GrayCode\ReadMe.txt
del C:\Users\gsaini\Documents\GitHub\Algo\Interleave\Interleave\ReadMe.txt
del C:\Users\gsaini\Documents\GitHub\Algo\PassportTrial\PassportTrial\ReadMe.txt
del C:\Users\gsaini\Documents\GitHub\Algo\Permutation\Permutation\ReadMe.txt
del C:\Users\gsaini\Documents\GitHub\Algo\PowerOf2\PowerOf2\ReadMe.txt
del C:\Users\gsaini\Documents\GitHub\Algo\ProducerConsumer\ProducerConsumer\ReadMe.txt
del C:\Users\gsaini\Documents\GitHub\Algo\QueueUsingTwoSTacks\QueueUsingTwoSTacks\ReadMe.txt
del C:\Users\gsaini\Documents\GitHub\Algo\RansomNote\RansomNote\ReadMe.txt
del C:\Users\gsaini\Documents\GitHub\Algo\Stock\Stock\ReadMe.txt
del C:\Users\gsaini\Documents\GitHub\Algo\Test\Test\ReadMe.txt
del C:\Users\gsaini\Documents\GitHub\Algo\TRIANGLE\TRIANGLE\ReadMe.txt
del C:\Users\gsaini\Documents\GitHub\Algo\Trie\Trie\ReadMe.txt
del C:\Users\gsaini\Documents\GitHub\Algo\Unique_Elements\Unique_Elements\ReadMe.txt
del C:\Users\gsaini\Documents\GitHub\Algo\WaterArea\WaterArea\ReadMe.txt
