del C:\Users\gsaini\Documents\GitHub\Algo\Anagrams\Anagrams\stdafx.h
del C:\Users\gsaini\Documents\GitHub\Algo\Anagrams\Anagrams\targetver.h
del C:\Users\gsaini\Documents\GitHub\Algo\BalancedBrackets\BalancedBrackets\stdafx.h
del C:\Users\gsaini\Documents\GitHub\Algo\BalancedBrackets\BalancedBrackets\targetver.h
del C:\Users\gsaini\Documents\GitHub\Algo\BooksAndStudent\BooksAndStudent\stdafx.h
del C:\Users\gsaini\Documents\GitHub\Algo\BooksAndStudent\BooksAndStudent\targetver.h
del C:\Users\gsaini\Documents\GitHub\Algo\BST\BST\stdafx.h
del C:\Users\gsaini\Documents\GitHub\Algo\BST\BST\targetver.h
del C:\Users\gsaini\Documents\GitHub\Algo\Cycle\Cycle\stdafx.h
del C:\Users\gsaini\Documents\GitHub\Algo\Cycle\Cycle\targetver.h
del C:\Users\gsaini\Documents\GitHub\Algo\Graph\Graph\stdafx.h
del C:\Users\gsaini\Documents\GitHub\Algo\Graph\Graph\targetver.h
del C:\Users\gsaini\Documents\GitHub\Algo\GrayCode\GrayCode\stdafx.h
del C:\Users\gsaini\Documents\GitHub\Algo\GrayCode\GrayCode\targetver.h
del C:\Users\gsaini\Documents\GitHub\Algo\Interleave\Interleave\stdafx.h
del C:\Users\gsaini\Documents\GitHub\Algo\Interleave\Interleave\targetver.h
del C:\Users\gsaini\Documents\GitHub\Algo\PassportTrial\PassportTrial\stdafx.h
del C:\Users\gsaini\Documents\GitHub\Algo\PassportTrial\PassportTrial\targetver.h
del C:\Users\gsaini\Documents\GitHub\Algo\Permutation\Permutation\stdafx.h
del C:\Users\gsaini\Documents\GitHub\Algo\Permutation\Permutation\targetver.h
del C:\Users\gsaini\Documents\GitHub\Algo\PowerOf2\PowerOf2\stdafx.h
del C:\Users\gsaini\Documents\GitHub\Algo\PowerOf2\PowerOf2\targetver.h
del C:\Users\gsaini\Documents\GitHub\Algo\ProducerConsumer\ProducerConsumer\stdafx.h
del C:\Users\gsaini\Documents\GitHub\Algo\ProducerConsumer\ProducerConsumer\targetver.h
del C:\Users\gsaini\Documents\GitHub\Algo\QueueUsingTwoSTacks\QueueUsingTwoSTacks\stdafx.h
del C:\Users\gsaini\Documents\GitHub\Algo\QueueUsingTwoSTacks\QueueUsingTwoSTacks\targetver.h
del C:\Users\gsaini\Documents\GitHub\Algo\RansomNote\RansomNote\stdafx.h
del C:\Users\gsaini\Documents\GitHub\Algo\RansomNote\RansomNote\targetver.h
del C:\Users\gsaini\Documents\GitHub\Algo\Stock\Stock\stdafx.h
del C:\Users\gsaini\Documents\GitHub\Algo\Stock\Stock\targetver.h
del C:\Users\gsaini\Documents\GitHub\Algo\Test\Test\stdafx.h
del C:\Users\gsaini\Documents\GitHub\Algo\Test\Test\targetver.h
del C:\Users\gsaini\Documents\GitHub\Algo\TRIANGLE\TRIANGLE\stdafx.h
del C:\Users\gsaini\Documents\GitHub\Algo\TRIANGLE\TRIANGLE\targetver.h
del C:\Users\gsaini\Documents\GitHub\Algo\Trie\Trie\stdafx.h
del C:\Users\gsaini\Documents\GitHub\Algo\Trie\Trie\targetver.h
del C:\Users\gsaini\Documents\GitHub\Algo\Unique_Elements\Unique_Elements\stdafx.h
del C:\Users\gsaini\Documents\GitHub\Algo\Unique_Elements\Unique_Elements\targetver.h
del C:\Users\gsaini\Documents\GitHub\Algo\WaterArea\WaterArea\stdafx.h
del C:\Users\gsaini\Documents\GitHub\Algo\WaterArea\WaterArea\targetver.h
